### ISSUE TITLE
Incompatibility with Advanced BBCode Box

### ISSUE THREAD

**Issue by Draky50110** [rxu/posts_merging#23]
Hello.

There is a small problem with another EXT : ABBC3.

As seen here : https://lut.im/hlZN735X/Rl7wlPxK

Other BBCodes than "basic ones" are not displayed to chosse a separator in extension tab (admin).
Grey boxes are displayed above.

**Comment by Galixte** [comment]
Hi @rxu,

could you take a look please ?
