### ISSUE TITLE
Error when sending post to merge. (via Quick Reply)

### ISSUE THREAD

**Issue by jakubsuchybio** [rxu/posts_merging#26]
Hi, when I send a new reply this error pops up:
```
[phpBB Debug] PHP Warning: in file [ROOT]/phpbb/search/fulltext_native.php on line 107: Missing argument 8 for phpbb/search/fulltext_native::__construct(), called in [ROOT]/ext/rxu/PostsMerging/core/helper.php on line 261 and defined
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions.php on line 2412: Cannot modify header information - headers already sent by (output started at [ROOT]/includes/functions.php:3899)
```
When I hit Refresh, the error stays and new post is duplicated.
When I don't Refresh and navigate to the new post via address bar, the new message looks fine (so it sent the new post)

If you need any more debug info, just ask.
Regards, Biosek.

**Comment by rxu** [comment]
This was already fixed, see https://github.com/rxu/posts_merging/commit/d7d53e8bf3a65ea2d53b327f9323a3cc7ebf14d2

Thanks for reporting.

**Comment by jakubsuchybio** [comment]
I see. I reported it because my forum was on release no. 2.0.2 which is your last release on GitHub.
So maybe I would suggest to create new release maybe?
With latest version from master branch it works fine.
Thanks

**Comment by rxu** [comment]
> So maybe I would suggest to create new release maybe?

That is in plans, yes. Although I have no estimate release timespan for now.
